export const PANTRY_LIST_REQUEST = "PANTRY_LIST_REQUEST";
export const PANTRY_LIST_SUCCESS = "PANTRY_LIST_SUCCESS";
export const PANTRY_LIST_FAIL ="PANTRY_LIST_FAIL";

export const PANTRY_CREATE_REQUEST = "PANTRY_CREATE_REQUEST";
export const PANTRY_CREATE_SUCCESS = "PANTRY_CREATE_SUCCESS";
export const PANTRY_CREATE_FAIL ="PANTRY_CREATE_FAIL";

export const PANTRY_DELETE_SUCCESS = "PANTRY_DELETE_SUCCESS";
export const PANTRY_DELETE_REQUEST = "PANTRY_DELETE_REQUEST";
export const PANTRY_DELETE_FAIL ="PANTRY_DELETE_FAIL";


